### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ckipp01** [creativescala/creative-scala.org#1]
Hey! First off, this project is great. I stumbled across this while looking looking for generative art/processing libraries in Scala, and then this library caught my attention. It's been really fun to play around with so far!

I was reading through the online book, and I'm assuming that it's been generated some how, but if we come across broken links or such in the html version of the book, would you prefer a pr on this repo for them, or is there another repo that hold the info that you're generating the html from?

Cheers!

**Comment by noelwelsh** [comment]
Hi! Great to hear you're enjoying Doodle and Creative Scala. The relevant repositories are:

* the library, Doodle: https://github.com/creativescala/doodle
* the book, Creative Scala: https://github.com/underscoreio/creative-scala

(Why is Creative Scala not under the Creative Scala github organisation? No good reason. Just haven't got around to it yet.)

**Comment by noelwelsh** [comment]
To actually answer your question, a PR on the correct repo is preferred.
